//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.16 at 04:44:21 PM EST 
//


package org.example.megaballs;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.example.megaballs package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MegaBalls_QNAME = new QName("http://www.example.org/MegaBalls", "MegaBalls");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.example.megaballs
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MegaBalls }
     * 
     */
    public MegaBalls createMegaBalls() {
        return new MegaBalls();
    }

    /**
     * Create an instance of {@link Numbers }
     * 
     */
    public Numbers createNumbers() {
        return new Numbers();
    }

    /**
     * Create an instance of {@link MegaBall }
     * 
     */
    public MegaBall createMegaBall() {
        return new MegaBall();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MegaBalls }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/MegaBalls", name = "MegaBalls")
    public JAXBElement<MegaBalls> createMegaBalls(MegaBalls value) {
        return new JAXBElement<MegaBalls>(_MegaBalls_QNAME, MegaBalls.class, null, value);
    }

}
