//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.16 at 04:44:21 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/MegaBalls", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.example.megaballs;
