//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.21 at 11:23:24 AM EST 
//


package org.example.numbers_hit;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Count complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Count"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Number_Hits" type="{http://www.example.org/Numbers_Hit}Number_Hits" maxOccurs="unbounded"/&gt;
 *         &lt;element name="Mega_Hits" type="{http://www.example.org/Numbers_Hit}Mega_Hits" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "Count")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Count", propOrder = {
    "numberHits",
    "megaHits"
})
public class Count {

    @XmlElement(name = "Number_Hits", required = true)
    protected List<NumberHits> numberHits;
    @XmlElement(name = "Mega_Hits", required = true)
    protected List<MegaHits> megaHits;

    /**
     * Gets the value of the numberHits property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the numberHits property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNumberHits().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NumberHits }
     * 
     * 
     */
    public List<NumberHits> getNumberHits() {
        if (numberHits == null) {
            numberHits = new ArrayList<NumberHits>();
        }
        return this.numberHits;
    }

    /**
     * Gets the value of the megaHits property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the megaHits property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMegaHits().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MegaHits }
     * 
     * 
     */
    public List<MegaHits> getMegaHits() {
        if (megaHits == null) {
            megaHits = new ArrayList<MegaHits>();
        }
        return this.megaHits;
    }

}
